#pragma once

enum IS_WHERE
{
	CHANNAL_SELECT=1, ROOM_SELECT, ROOM_IN, GAME_PLAY
};

enum COMMAND_TYPE
{
	REQUEST_LOGIN = 1, ANSWER_LOGIN
};

enum CANNEL_STATE
{
	CHANNEL_USER_LOW=1, CHANNEL_USER_MID, CHANNEL_USER_HIGH, CHANNEL_USER_FULL
};

const int MAX_USER_NAME = 20;
const int BUF_SIZE = 1024;
const int MAX_SOCKET = 4;
const int MAX_CHANNEL = 2;
const int MAX_CHANNEL_USER = 30;
